defmodule FacilityType do
  @moduledoc """
  Responsible for defining Facility Type structs
  """
  defstruct is_medical: nil,
            is_retail: nil,
            is_hemp: nil,
            restrict_harvest_plant_restore_time_hours: nil,
            total_member_patients_allowed: nil,
            can_grow_plants: nil,
            can_create_opening_balance_plant_batches: nil,
            can_tag_plant_batches: nil,
            can_assign_locations_to_plant_batches: nil,
            plants_require_patient_affiliation: nil,
            plant_batches_can_contain_mother_plants: nil,
            can_update_plant_strains: nil,
            can_track_vegetative_plants: nil,
            can_create_immature_plant_packages_from_plants: nil,
            can_package_vegetative_plants: nil,
            can_package_waste: nil,
            can_report_harvest_schedules: nil,
            can_submit_harvests_for_testing: nil,
            can_require_harvest_sample_lab_test_batches: nil,
            can_create_opening_balance_packages: nil,
            can_create_derived_packages: nil,
            can_assign_locations_to_packages: nil,
            can_update_locations_on_packages: nil,
            packages_require_patient_affiliation: nil,
            can_create_trade_sample_packages: nil,
            can_donate_packages: nil,
            can_submit_packages_for_testing: nil,
            can_create_process_validation_packages: nil,
            can_require_package_sample_lab_test_batches: nil,
            can_request_product_remediation: nil,
            can_remediate_packages_with_failed_lab_results: nil,
            can_infuse_products: nil,
            can_test_packages: nil,
            can_transfer_from_external_facilities: nil,
            can_sell_to_consumers: nil,
            can_sell_to_patients: nil,
            can_sell_to_external_patients: nil,
            can_sell_to_caregivers: nil,
            advanced_sales: nil,
            sales_require_patient_number: nil,
            sales_require_external_patient_number: nil,
            sales_require_external_patient_identification_method: nil,
            sales_require_caregiver_number: nil,
            sales_require_caregiver_patient_number: nil,
            can_deliver_sales_to_consumers: nil,
            sales_delivery_require_consumer_id: nil,
            can_deliver_sales_to_patients: nil,
            sales_delivery_require_patient_number: nil,
            sales_delivery_require_recipient_name: nil,
            can_have_member_patients: nil,
            can_report_patient_check_ins: nil,
            can_specify_patient_sales_limit_exemption: nil,
            can_report_patient_adverse_responses: nil,
            can_report_strain_properties: nil
end

defimpl StructProtocol, for: FacilityType do
  def map_to_struct(%FacilityType{}, map) do
    struct(FacilityType, %{
      is_medical: Map.get(map, "IsMedical"),
      is_retail: Map.get(map, "IsRetail"),
      is_hemp: Map.get(map, "IsHemp"),
      restrict_harvest_plant_restore_time_hours:
        Map.get(map, "RestrictHarvestPlantRestoreTimeHours"),
      total_member_patients_allowed: Map.get(map, "TotalMemberPatientsAllowed"),
      can_grow_plants: Map.get(map, "CanGrowPlants"),
      can_create_opening_balance_plant_batches:
        Map.get(map, "CanCreateOpeningBalancePlantBatches"),
      can_tag_plant_batches: Map.get(map, "CanTagPlantBatches"),
      can_assign_locations_to_plant_batches: Map.get(map, "CanAssignLocationsToPlantBatches"),
      plants_require_patient_affiliation: Map.get(map, "PlantsRequirePatientAffiliation"),
      plant_batches_can_contain_mother_plants: Map.get(map, "PlantBatchesCanContainMotherPlants"),
      can_update_plant_strains: Map.get(map, "CanUpdatePlantStrains"),
      can_track_vegetative_plants: Map.get(map, "CanTrackVegetativePlants"),
      can_create_immature_plant_packages_from_plants:
        Map.get(map, "CanCreateImmaturePlantPackagesFromPlants"),
      can_package_vegetative_plants: Map.get(map, "CanPackageVegetativePlants"),
      can_package_waste: Map.get(map, "CanPackageWaste"),
      can_report_harvest_schedules: Map.get(map, "CanReportHarvestSchedules"),
      can_submit_harvests_for_testing: Map.get(map, "CanSubmitHarvestsForTesting"),
      can_require_harvest_sample_lab_test_batches:
        Map.get(map, "CanRequireHarvestSampleLabTestBatches"),
      can_create_opening_balance_packages: Map.get(map, "CanCreateOpeningBalancePackages"),
      can_create_derived_packages: Map.get(map, "CanCreateDerivedPackages"),
      can_assign_locations_to_packages: Map.get(map, "CanAssignLocationsToPackages"),
      can_update_locations_on_packages: Map.get(map, "CanUpdateLocationsOnPackages"),
      packages_require_patient_affiliation: Map.get(map, "PackagesRequirePatientAffiliation"),
      can_create_trade_sample_packages: Map.get(map, "CanCreateTradeSamplePackages"),
      can_donate_packages: Map.get(map, "CanDonatePackages"),
      can_submit_packages_for_testing: Map.get(map, "CanSubmitPackagesForTesting"),
      can_create_process_validation_packages: Map.get(map, "CanCreateProcessValidationPackages"),
      can_require_package_sample_lab_test_batches:
        Map.get(map, "CanRequirePackageSampleLabTestBatches"),
      can_request_product_remediation: Map.get(map, "CanRequestProductRemediation"),
      can_remediate_packages_with_failed_lab_results:
        Map.get(map, "CanRemediatePackagesWithFailedLabResults"),
      can_infuse_products: Map.get(map, "CanInfuseProducts"),
      can_test_packages: Map.get(map, "CanTestPackages"),
      can_transfer_from_external_facilities: Map.get(map, "CanTransferFromExternalFacilities"),
      can_sell_to_consumers: Map.get(map, "CanSellToConsumers"),
      can_sell_to_patients: Map.get(map, "CanSellToPatients"),
      can_sell_to_external_patients: Map.get(map, "CanSellToExternalPatients"),
      can_sell_to_caregivers: Map.get(map, "CanSellToCaregivers"),
      advanced_sales: Map.get(map, "AdvancedSales"),
      sales_require_patient_number: Map.get(map, "SalesRequirePatientNumber"),
      sales_require_external_patient_number: Map.get(map, "SalesRequireExternalPatientNumber"),
      sales_require_external_patient_identification_method:
        Map.get(map, "SalesRequireExternalPatientIdentificationMethod"),
      sales_require_caregiver_number: Map.get(map, "SalesRequireCaregiverNumber"),
      sales_require_caregiver_patient_number: Map.get(map, "SalesRequireCaregiverPatientNumber"),
      can_deliver_sales_to_consumers: Map.get(map, "CanDeliverSalesToConsumers"),
      sales_delivery_require_consumer_id: Map.get(map, "SalesDeliveryRequireConsumerId"),
      can_deliver_sales_to_patients: Map.get(map, "CanDeliverSalesToPatients"),
      sales_delivery_require_patient_number: Map.get(map, "SalesDeliveryRequirePatientNumber"),
      sales_delivery_require_recipient_name: Map.get(map, "SalesDeliveryRequireRecipientName"),
      can_have_member_patients: Map.get(map, "CanHaveMemberPatients"),
      can_report_patient_check_ins: Map.get(map, "CanReportPatientCheckIns"),
      can_specify_patient_sales_limit_exemption:
        Map.get(map, "CanSpecifyPatientSalesLimitExemption"),
      can_report_patient_adverse_responses: Map.get(map, "CanReportPatientsAdverseResponses"),
      can_report_strain_properties: Map.get(map, "CanReportStrainProperties")
    })
  end
end
